export const tableData = [
  {
    location: "chr17:41276045",
    gene: "BRCA1",
    genomicsAndGeneticInformation: {
      REF: "C",
      ALT: "T",
      AA: "Arg",
      ZYGOSITY: "HET",
      codon: "",
    },
    ACMG: {
      DOM: "",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 120,
      "Alt(%)": "40",
    },
    clinicalEvidence: {
      Pheno: "Breast cancer",
      matchedPhenotypes: "Yes",
      CLINVAR: "Pathogenic",
      OMIM: "604370",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Moderate",
    },
    inHouse: {
      V: "Confirmed",
      G: "Positive",
      "AF%": "0.5",
    },
    effectAndPrediction: {
      EFFECT: "Missense",
      Sev: "High",
      "CADD(PHRED)": 28,
      "Splice-AI": "Neutral",
    },
    frequency: {
      "Max AF(%)": "0.2",
      "GNEv4 AF(%)": "0.15",
      "GNGv4 AF(%)": "0.18",
    },
  },
  {
    location: "chr17:7579472",
    gene: "TP53",
    genomicsAndGeneticInformation: {
      REF: "G",
      ALT: "A",
      AA: "Arg",
      ZYGOSITY: "HOM",
      codon: "Gga/Aga",
    },
    ACMG: {
      DOM: "LP",
      ACMGCLASSIFICATION: "LP",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 135,
      "Alt(%)": "55",
    },
    clinicalEvidence: {
      Pheno: "Li-Fraumeni syndrome",
      matchedPhenotypes: "Yes",
      CLINVAR: "Likely Pathogenic",
      OMIM: "191170",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Strong",
    },
    inHouse: {
      V: "Validated",
      G: "Positive",
      "AF%": "0.8",
    },
    effectAndPrediction: {
      EFFECT: "Missense",
      Sev: "Moderate",
      "CADD(PHRED)": 22,
      "Splice-AI": "Minor",
    },
    frequency: {
      "Max AF(%)": "0.3",
      "GNEv4 AF(%)": "0.25",
      "GNGv4 AF(%)": "0.28",
    },
  },
  {
    location: "chr7:55249071",
    gene: "EGFR",
    genomicsAndGeneticInformation: {
      REF: "A",
      ALT: "G",
      AA: "Gly",
      ZYGOSITY: "HET",
      codon: "Gga/Aga",
    },
    ACMG: {
      DOM: "VUS",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Fail",
      DP2: 100,
      "Alt(%)": "35",
    },
    clinicalEvidence: {
      Pheno: "Lung cancer",
      matchedPhenotypes: "Partial",
      CLINVAR: "Pathogenic",
      OMIM: "131550",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Limited",
    },
    inHouse: {
      V: "Not Validated",
      G: "Negative",
      "AF%": "0.3",
    },
    effectAndPrediction: {
      EFFECT: "Missense",
      Sev: "High",
      "CADD(PHRED)": 30,
      "Splice-AI": "No effect",
    },
    frequency: {
      "Max AF(%)": "0.4",
      "GNEv4 AF(%)": "0.35",
      "GNGv4 AF(%)": "0.38",
    },
  },
  {
    location: "chr12:25398284",
    gene: "KRAS",
    genomicsAndGeneticInformation: {
      REF: "G",
      ALT: "T",
      AA: "Gly",
      ZYGOSITY: "HET",
      codon: "",
    },
    ACMG: {
      DOM: "LP",
      ACMGCLASSIFICATION: "LP",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 145,
      "Alt(%)": "50",
    },
    clinicalEvidence: {
      Pheno: "Colorectal cancer",
      matchedPhenotypes: "Yes",
      CLINVAR: "Pathogenic",
      OMIM: "190070",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Extensive",
    },
    inHouse: {
      V: "Validated",
      G: "Positive",
      "AF%": "0.6",
    },
    effectAndPrediction: {
      EFFECT: "Missense",
      Sev: "High",
      "CADD(PHRED)": 26,
      "Splice-AI": "No impact",
    },
    frequency: {
      "Max AF(%)": "0.5",
      "GNEv4 AF(%)": "0.45",
      "GNGv4 AF(%)": "0.47",
    },
  },
  {
    location: "chr3:37034807",
    gene: "MLH1",
    genomicsAndGeneticInformation: {
      REF: "T",
      ALT: "C",
      AA: "Ser",
      ZYGOSITY: "HOM",
      codon: "",
    },
    ACMG: {
      DOM: "VUS",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 110,
      "Alt(%)": "42",
    },
    clinicalEvidence: {
      Pheno: "Lynch syndrome",
      matchedPhenotypes: "Yes",
      CLINVAR: "Likely Pathogenic",
      OMIM: "120436",
      "OMIM Inheritance": "Autosomal Recessive",
      LitVar2: "Moderate",
    },
    inHouse: {
      V: "Validated",
      G: "Positive",
      "AF%": "0.7",
    },
    effectAndPrediction: {
      EFFECT: "Nonsense",
      Sev: "High",
      "CADD(PHRED)": 35,
      "Splice-AI": "Predicted loss",
    },
    frequency: {
      "Max AF(%)": "0.2",
      "GNEv4 AF(%)": "0.18",
      "GNGv4 AF(%)": "0.20",
    },
  },
  {
    location: "chr2:47630513",
    gene: "MSH2",
    genomicsAndGeneticInformation: {
      REF: "A",
      ALT: "G",
      AA: "Arg",
      ZYGOSITY: "HET",
      codon: "",
    },
    ACMG: {
      DOM: "VUS",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 130,
      "Alt(%)": "38",
    },
    clinicalEvidence: {
      Pheno: "Lynch syndrome",
      matchedPhenotypes: "Yes",
      CLINVAR: "Pathogenic",
      OMIM: "609309",
      "OMIM Inheritance": "Autosomal Recessive",
      LitVar2: "Strong",
    },
    inHouse: {
      V: "Validated",
      G: "Confirmed",
      "AF%": "0.4",
    },
    effectAndPrediction: {
      EFFECT: "Frameshift",
      Sev: "High",
      "CADD(PHRED)": 32,
      "Splice-AI": "Altered splicing",
    },
    frequency: {
      "Max AF(%)": "0.3",
      "GNEv4 AF(%)": "0.25",
      "GNGv4 AF(%)": "0.27",
    },
  },
  {
    location: "chr5:112175434",
    gene: "APC",
    genomicsAndGeneticInformation: {
      REF: "G",
      ALT: "T",
      AA: "Trp",
      ZYGOSITY: "HET",
      codon: "ctC/ctT",
    },
    ACMG: {
      DOM: "VUS",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 140,
      "Alt(%)": "47",
    },
    clinicalEvidence: {
      Pheno: "Familial adenomatous polyposis",
      matchedPhenotypes: "Yes",
      CLINVAR: "Pathogenic",
      OMIM: "175100",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Extensive",
    },
    inHouse: {
      V: "Validated",
      G: "Confirmed",
      "AF%": "0.5",
    },
    effectAndPrediction: {
      EFFECT: "Frameshift",
      Sev: "High",
      "CADD(PHRED)": 34,
      "Splice-AI": "Significant",
    },
    frequency: {
      "Max AF(%)": "0.3",
      "GNEv4 AF(%)": "0.28",
      "GNGv4 AF(%)": "0.30",
    },
  },
  {
    location: "chr17:29500000",
    gene: "NF1",
    genomicsAndGeneticInformation: {
      REF: "T",
      ALT: "C",
      AA: "Leu",
      ZYGOSITY: "HET",
      codon: "ctC/ctT",
    },
    ACMG: {
      DOM: "LP",
      ACMGCLASSIFICATION: "LP",
    },
    variantCallingQR: {
      "Q&R": "Fail",
      DP2: 105,
      "Alt(%)": "33",
    },
    clinicalEvidence: {
      Pheno: "Neurofibromatosis type 1",
      matchedPhenotypes: "Yes",
      CLINVAR: "Likely Pathogenic",
      OMIM: "162200",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Moderate",
    },
    inHouse: {
      V: "Not Validated",
      G: "Negative",
      "AF%": "0.6",
    },
    effectAndPrediction: {
      EFFECT: "Splice site",
      Sev: "Moderate",
      "CADD(PHRED)": 20,
      "Splice-AI": "Predicted impact",
    },
    frequency: {
      "Max AF(%)": "0.4",
      "GNEv4 AF(%)": "0.35",
      "GNGv4 AF(%)": "0.38",
    },
  },
  {
    location: "chr10:89692913",
    gene: "PTEN",
    genomicsAndGeneticInformation: {
      REF: "C",
      ALT: "A",
      AA: "His",
      ZYGOSITY: "HET",
      codon: "",
    },
    ACMG: {
      DOM: "VUS",
      ACMGCLASSIFICATION: "VUS",
    },
    variantCallingQR: {
      "Q&R": "Pass",
      DP2: 125,
      "Alt(%)": "52",
    },
    clinicalEvidence: {
      Pheno: "Cowden syndrome",
      matchedPhenotypes: "Yes",
      CLINVAR: "Pathogenic",
      OMIM: "601728",
      "OMIM Inheritance": "Autosomal Dominant",
      LitVar2: "Strong",
    },
    inHouse: {
      V: "Validated",
      G: "Positive",
      "AF%": "0.7",
    },
    effectAndPrediction: {
      EFFECT: "Missense",
      Sev: "High",
      "CADD(PHRED)": 27,
      "Splice-AI": "No impact",
    },
    frequency: {
      "Max AF(%)": "0.2",
      "GNEv4 AF(%)": "0.18",
      "GNGv4 AF(%)": "0.20",
    },
  },
];
